language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - "pip install coverage"
  - "pip install coveralls"
  - "python setup.py install"
script: coverage run --branch --include=*pylinq* tests
after_success: coveralls