language: python
python:
  - "2.7"
  - "2.6"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - "pip install coverage"
  - "pip install coveralls"
  - "python setup.py install"
script: coverage run --branch --include=*pinq* --omit=*tests* tests
after_success: coveralls